# Generated by Django 4.2.3 on 2023-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brName', models.CharField(max_length=100)),
                ('brImg', models.ImageField(upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='counterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmCounter', models.CharField(max_length=100)),
                ('nmNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reviewList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayarName', models.CharField(max_length=100)),
                ('bayarLoct', models.CharField(max_length=100)),
                ('bayarImg', models.ImageField(upload_to='reviw')),
                ('bayarDisc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='teamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamImg', models.ImageField(upload_to='team')),
                ('teamName', models.CharField(max_length=100)),
                ('teamTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
