# Generated by Django 4.2.3 on 2023-07-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('pages', '0003_packagelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proIimg', models.ImageField(upload_to='project')),
                ('proTitle', models.CharField(max_length=100)),
                ('proUrl', models.URLField()),
                ('proCata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
