# Generated by Django 4.2.2 on 2023-09-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_projectlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='counterAbout',
        ),
    ]
