# Generated by Django 4.2.2 on 2023-09-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_counterabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagelist',
            name='pkgDisc',
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist1',
            field=models.CharField(default=5, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist2',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist3',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist4',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist5',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagelist',
            name='pkglist6',
            field=models.CharField(default='1', max_length=35),
            preserve_default=False,
        ),
    ]
