# Generated by Django 4.2.2 on 2023-08-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_details', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, unique=True)),
                ('blog_slug', models.SlugField(max_length=100, unique=True)),
                ('blog_image', models.ImageField(upload_to='blog')),
                ('blog_sortText', models.CharField(max_length=96)),
                ('blog_longText', models.TextField(max_length=700)),
                ('blog_author', models.CharField(max_length=50)),
                ('blog_publishDate', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_item_category')),
            ],
        ),
    ]
