# Generated by Django 4.2.2 on 2023-09-19 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_model_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item_category',
            name='category_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
