# Generated by Django 4.2.2 on 2023-09-19 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_item_category_category_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='blog_longText',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
