# Generated by Django 4.2.3 on 2023-07-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivary_time',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
