# Generated by Django 4.2.3 on 2023-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_delivary_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sm_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
