# Generated by Django 4.2.2 on 2023-08-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_sm_description_alter_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category',
            new_name='Service_category',
        ),
    ]
