# Generated by Django 4.2.2 on 2023-09-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=12)),
                ('contact_icon', models.ImageField(upload_to='social_icon')),
                ('contact_addres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='social_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=15, unique=True)),
                ('social_icon', models.ImageField(upload_to='social_icon')),
                ('social_url', models.URLField()),
            ],
        ),
    ]
