# Generated by Django 4.2.2 on 2023-09-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_address',
            name='contact_icon',
            field=models.FileField(upload_to='social_icon'),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='social_icon',
            field=models.FileField(upload_to='social_icon'),
        ),
    ]
