# Generated by Django 4.2.2 on 2023-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_contact_address_contact_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_logo', models.FileField(upload_to='logo')),
            ],
        ),
    ]
